// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Grpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcServer {
  public static partial class TestEF
  {
    static readonly string __ServiceName = "GrpcServer.TestEF";

    static readonly grpc::Marshaller<global::GrpcServer.AddUserRequest> __Marshaller_GrpcServer_AddUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServer.AddUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GrpcServer.AddUserResponse> __Marshaller_GrpcServer_AddUserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GrpcServer.AddUserResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GrpcServer.AddUserRequest, global::GrpcServer.AddUserResponse> __Method_AddUsers = new grpc::Method<global::GrpcServer.AddUserRequest, global::GrpcServer.AddUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddUsers",
        __Marshaller_GrpcServer_AddUserRequest,
        __Marshaller_GrpcServer_AddUserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcServer.GrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TestEF</summary>
    public abstract partial class TestEFBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GrpcServer.AddUserResponse> AddUsers(global::GrpcServer.AddUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TestEF</summary>
    public partial class TestEFClient : grpc::ClientBase<TestEFClient>
    {
      /// <summary>Creates a new client for TestEF</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TestEFClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TestEF that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TestEFClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TestEFClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TestEFClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GrpcServer.AddUserResponse AddUsers(global::GrpcServer.AddUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUsers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GrpcServer.AddUserResponse AddUsers(global::GrpcServer.AddUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddUsers, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServer.AddUserResponse> AddUsersAsync(global::GrpcServer.AddUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddUsersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GrpcServer.AddUserResponse> AddUsersAsync(global::GrpcServer.AddUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddUsers, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TestEFClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TestEFClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TestEFBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddUsers, serviceImpl.AddUsers).Build();
    }

  }
}
#endregion
